### ISSUE TITLE
How to authenticate user through voice?

### ISSUE THREAD

**Issue by alexxvu** [dlvcsulb/CSULB-Design-491-Let-s-Talk#10]
Google has the ability to recognize voice and only allow users to do things if the voice is permitted. How do we incorporate this into our app?

**Comment by MarkSaa** [comment]
Option: recognize user form given name by voice, then a texted based answer for password.

**Comment by dlvcsulb** [comment]
Google Voice Match will be the implementation here along with Google SSO.

**Comment by dlvcsulb** [comment]
To simplify we will also prompt for permission at this stage.

**Comment by MarkSaa** [comment]
When the the program starts, the application requests the users name to confirm who's journal we will be accessing.
