### ISSUE TITLE
Implement web hosting

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#11]
Start a herokuapp web instance.

**Comment by jasonjyk** [comment]
https://letstalk491.000webhostapp.com/
Prototype website

**Comment by jasonjyk** [comment]
We can just take it and move it to another webhost

**Comment by dlvcsulb** [comment]
Heroku instance set up as well. Will migrate over upon completion of web interface.
