### ISSUE TITLE
Fix conversational loop for unknown input

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#2]
When in a conversation, if the user provides a response which Let's Talk cannot parse, it will break and be unable to recover.

**Comment by dlvcsulb** [comment]
This only happens in a specific loop sequence. Will need to see why this sequence isn't working like the others.

**Comment by MarkSaa** [comment]
Current interface problem. There is no recursive function. One has been created but is not working properly

**Comment by MarkSaa** [comment]
I'm re organizing how the intents are handled. This not only is cleaning up the conversation, but is also handling any potential outcome/response correctly
