### ISSUE TITLE
Work on final presentation

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#23]
Due 12/4, 12:00 pm

**Comment by dlvcsulb** [comment]
Made preliminary document for outline. We'll fill this out with our notes and use that to structure the actual presentation.

**Comment by alexxvu** [comment]
Working on it

**Comment by dlvcsulb** [comment]
Created the offline demo and finalized the slides.

**Comment by dlvcsulb** [comment]
Submitted final PPT to Dropbox.
