### ISSUE TITLE
User Consent

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#4]
Research what types of consent we need to obtain from the user in order to collect data on them while minimizing risk of litigation for the team.

**Comment by dlvcsulb** [comment]
Created a Google Site page to temporarily host a privacy policy page while we get the actual site up. Still need to write up a more robust policy as well. Current state is enough for private, closed alpha testing by the development team for now.

**Comment by dlvcsulb** [comment]
Privacy policy is what Google and Dialogflow's ToS are (users are already in agreement with Google ToS if they are using the Assistant). Until we start collecting into db, it is not a concern.

**Comment by dlvcsulb** [comment]
Mark is working in permissions approval into first-launch use of the Action.

**Comment by MarkSaa** [comment]
I added in approval question that each new user must answer before continuing with the application. It's 3 simple questions that the user can answer with yes/no/I understand/I dont understand, and is handled accordingly.
