### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#5]
Publishing on the Google Assistant marketplace requires a proper privacy policy that is hosted on the web.

Can work hand-in-hand with issue #4.

**Comment by jasonjyk** [comment]
Since we have Google Assistant test box on our website, we'll need a textblock to pop up to notify users.

**Comment by jasonjyk** [comment]
Look into user consent and make sure we aren't liable.

**Comment by dlvcsulb** [comment]
We will push privacy policy at first sign in and also request user permission at this stage.

**Comment by jasonjyk** [comment]
we should have a popup notification on whatever website we choose to use for user consent

**Comment by MarkSaa** [comment]
privacy policy is tied in with the user consent
