### ISSUE TITLE
Fix exit condition

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#7]
Let's Talk does not cleanly exit, per Google's requirements for an Assistant action.

**Comment by dlvcsulb** [comment]
Looks like this is because we currently have multiple implementations that directly exit. Will need to consolidate them into one context, and then have context exit the app.

**Comment by MarkSaa** [comment]
fixed. The problem was due to lifespans of certain responses.
