### ISSUE TITLE
Shorter hook name

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#8]
Find a catchier and shorter name for users to use to enter the application from the Assistant main menu.

**Comment by alexxvu** [comment]
Since we are switching over to a Journal/diary type application, "All Ears" sounds like a good name for our app. It is short and makes sense. When users want to voice activate the app, all they would have to say is "Ok Google, Talk to "All Ears".

**Comment by dlvcsulb** [comment]
Too late in the semester to change it up. Going to stick with Let's Talk and find a way to creatively allow users to launch instead.

**Comment by dlvcsulb** [comment]
We'll be going with something along the lines of Let's Talk Journaling.
