### ISSUE TITLE
Prompt for user permission on first launch

### ISSUE THREAD

**Issue by dlvcsulb** [dlvcsulb/CSULB-Design-491-Let-s-Talk#9]
Have user explicitly agree to having data collection in the app before using the app for the first time. Store this result in the app db.

**Comment by jasonjyk** [comment]
We need it for our web too now that we have a test unit on the web

**Comment by dlvcsulb** [comment]
Looking into Google SSO for authentication. Web interface doesn't need a login because Dialogflow sandboxes it from the production environment.

**Comment by dlvcsulb** [comment]
Will actually tie this one in with Privacy Policy (issue #5) and user authentication (issue #10).
